# Generated by Django 5.2.3 on 2025-06-27 04:47

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=70)),
                ('location', models.IntegerField()),
                ('established_year', models.PositiveIntegerField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
