# Generated by Django 5.2.3 on 2025-06-27 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('position', models.CharField(max_length=80)),
                ('joined_at', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
